### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.cognitiveservices.language.textanalytics.models.error_response_py3.ErrorResponse
  - azure.cognitiveservices.language.textanalytics.models.error_response_py3.ErrorResponseException
  fullName: azure.cognitiveservices.language.textanalytics.models.error_response_py3
  langs:
  - python
  module: azure.cognitiveservices.language.textanalytics.models.error_response_py3
  name: error_response_py3
  source:
    id: error_response_py3
    path: azure-cognitiveservices-language-textanalytics\azure\cognitiveservices\language\textanalytics\models\error_response_py3.py
    remote:
      branch: master
      path: azure-cognitiveservices-language-textanalytics\azure\cognitiveservices\language\textanalytics\models\error_response_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.cognitiveservices.language.textanalytics.models.error_response_py3
references:
- fullName: azure.cognitiveservices.language.textanalytics.models.error_response_py3.ErrorResponse
  isExternal: false
  name: ErrorResponse
  parent: azure.cognitiveservices.language.textanalytics.models.error_response_py3
  uid: azure.cognitiveservices.language.textanalytics.models.error_response_py3.ErrorResponse
- fullName: azure.cognitiveservices.language.textanalytics.models.error_response_py3.ErrorResponseException
  isExternal: false
  name: ErrorResponseException
  parent: azure.cognitiveservices.language.textanalytics.models.error_response_py3
  uid: azure.cognitiveservices.language.textanalytics.models.error_response_py3.ErrorResponseException
