### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.cognitiveservices.vision.face.models.api_error_py3.APIError
  - azure.cognitiveservices.vision.face.models.api_error_py3.APIErrorException
  fullName: azure.cognitiveservices.vision.face.models.api_error_py3
  langs:
  - python
  module: azure.cognitiveservices.vision.face.models.api_error_py3
  name: api_error_py3
  source:
    id: api_error_py3
    path: azure-cognitiveservices-vision-face\azure\cognitiveservices\vision\face\models\api_error_py3.py
    remote:
      branch: master
      path: azure-cognitiveservices-vision-face\azure\cognitiveservices\vision\face\models\api_error_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.cognitiveservices.vision.face.models.api_error_py3
references:
- fullName: azure.cognitiveservices.vision.face.models.api_error_py3.APIError
  isExternal: false
  name: APIError
  parent: azure.cognitiveservices.vision.face.models.api_error_py3
  uid: azure.cognitiveservices.vision.face.models.api_error_py3.APIError
- fullName: azure.cognitiveservices.vision.face.models.api_error_py3.APIErrorException
  isExternal: false
  name: APIErrorException
  parent: azure.cognitiveservices.vision.face.models.api_error_py3
  uid: azure.cognitiveservices.vision.face.models.api_error_py3.APIErrorException
