### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.keyvault.models.key_vault_error_py3.KeyVaultError
  - azure.keyvault.models.key_vault_error_py3.KeyVaultErrorException
  fullName: azure.keyvault.models.key_vault_error_py3
  langs:
  - python
  module: azure.keyvault.models.key_vault_error_py3
  name: key_vault_error_py3
  source:
    id: key_vault_error_py3
    path: azure-keyvault\azure\keyvault\models\key_vault_error_py3.py
    remote:
      branch: master
      path: azure-keyvault\azure\keyvault\models\key_vault_error_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.keyvault.models.key_vault_error_py3
references:
- fullName: azure.keyvault.models.key_vault_error_py3.KeyVaultError
  isExternal: false
  name: KeyVaultError
  parent: azure.keyvault.models.key_vault_error_py3
  uid: azure.keyvault.models.key_vault_error_py3.KeyVaultError
- fullName: azure.keyvault.models.key_vault_error_py3.KeyVaultErrorException
  isExternal: false
  name: KeyVaultErrorException
  parent: azure.keyvault.models.key_vault_error_py3
  uid: azure.keyvault.models.key_vault_error_py3.KeyVaultErrorException
