### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.batch.models.batch_service_client_enums.ErrorCategory.server_error
  - azure.batch.models.batch_service_client_enums.ErrorCategory.user_error
  class: azure.batch.models.batch_service_client_enums.ErrorCategory
  fullName: azure.batch.models.batch_service_client_enums.ErrorCategory
  inheritance:
  - inheritance:
    - type: builtins.object
    type: enum.Enum
  langs:
  - python
  module: azure.batch.models.batch_service_client_enums
  name: ErrorCategory
  source:
    id: ErrorCategory
    path: azure-batch\azure\batch\models\batch_service_client_enums.py
    remote:
      branch: master
      path: azure-batch\azure\batch\models\batch_service_client_enums.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 142
  summary: 'An enumeration.



    '
  syntax: {}
  type: class
  uid: azure.batch.models.batch_service_client_enums.ErrorCategory
- class: azure.batch.models.batch_service_client_enums.ErrorCategory
  fullName: azure.batch.models.batch_service_client_enums.ErrorCategory.server_error
  id: server_error
  langs:
  - python
  module: azure.batch.models.batch_service_client_enums
  name: server_error
  parent: azure.batch.models.batch_service_client_enums.ErrorCategory
  source:
    id: server_error
    path: null
    remote:
      branch: master
      path: null
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: null
  summary: 'The error is due to an internal server issue.

    '
  syntax:
    content: server_error = 'servererror'
    return:
      type:
      - azure.batch.models.batch_service_client_enums.ErrorCategory
  type: attribute
  uid: azure.batch.models.batch_service_client_enums.ErrorCategory.server_error
- class: azure.batch.models.batch_service_client_enums.ErrorCategory
  fullName: azure.batch.models.batch_service_client_enums.ErrorCategory.user_error
  id: user_error
  langs:
  - python
  module: azure.batch.models.batch_service_client_enums
  name: user_error
  parent: azure.batch.models.batch_service_client_enums.ErrorCategory
  source:
    id: user_error
    path: null
    remote:
      branch: master
      path: null
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: null
  summary: 'The error is due to a user issue, such as misconfiguration.

    '
  syntax:
    content: user_error = 'usererror'
    return:
      type:
      - azure.batch.models.batch_service_client_enums.ErrorCategory
  type: attribute
  uid: azure.batch.models.batch_service_client_enums.ErrorCategory.user_error
references:
- fullName: azure.batch.models.batch_service_client_enums.ErrorCategory.server_error
  isExternal: false
  name: server_error
  parent: azure.batch.models.batch_service_client_enums.ErrorCategory
  uid: azure.batch.models.batch_service_client_enums.ErrorCategory.server_error
- fullName: azure.batch.models.batch_service_client_enums.ErrorCategory.user_error
  isExternal: false
  name: user_error
  parent: azure.batch.models.batch_service_client_enums.ErrorCategory
  uid: azure.batch.models.batch_service_client_enums.ErrorCategory.user_error
